version: "3.8"
   
services:
    redis:
        image: "redis:alpine"

    db:
        image: postgres:latest
        restart: always
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_DB=stockdb  
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres

    django:
        build: .
        container_name: django
        command: ./wait-for-db.sh
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
            - SQL_HOST=db
            - SQL_PORT=5432
        depends_on:
            - redis
            - db

    celery:
        build: .
        command: ./wait-for-django.sh
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - db
            - redis
            - django
    flower:
        build: .
        restart: always
        command: celery -A stockapi flower --address=0.0.0.0 --port=5566
        volumes:
            - .:/usr/src/app
        ports:
            - "5566:5566"
        depends_on:
            - celery

